#' Generating unrelated individuals with fiexed inbreding coeffs
#'
#' @param nb.inds number of (unrelated) individuals
#' @param haplos haplotype bed matrix
#' @param f inbreding coefficient
#' @param a parameter for the length of segments in HMM (in \eqn{cM^{-1}})
#' @param hbd.length mean length of HBD segments in cM
#' @param non.hbd.length mean length of non HBD segments in cM
#' @param tile.length tile length in cM
#' @param segments Logical. TRUE to get the position of HBD segments
#' 
#' @details Specify a and f or hbd.length and non.hbd.length, but not both.
#' This function uses a slightly imperfect method to generate individuals with a given HBD:
#' Haplotypes H1 and A are generated with tiles of mean length \code{tile.length}, then H2
#' is generated by taking tiles from H1 and A with mean lengthes \code{hbd.length} and \code{non.hbd.length}.
#' @details The HBD segments length are taken in an exponential distribution. If the parameters \code{hbd.length} and 
#' \code{non.hbd.length} are not specified, the mean HBD length is \eqn{\frac{1}{a(1-f)}}{1/(a(1-f))}
#' and the mean non-HBD length is \eqn{frac{1}{af}}{1/(af)}.
#' @details If \code{segments = TRUE} then a list of data frame giving the position of HBD segments (in cM) is returned.
#'
#' @return a list with components `bed.matrix`, `inbred.coef` (computed from the HBD length) 
#' and `segments` (if applicable).
#' @export
#'
#' @examples #' # installs KGH if not already installed
#' if(!require("KGH")) install.packages("KGH", repos="https://genostats.github.io/R/")
#' # loads a bed matrix of 1006 european haplotypes
#' filepath <- system.file("extdata", "1KG_haplos.bed", package = "KGH")
#' H <- read.bed.matrix(filepath)
#' # Generates a bed matrix with 100 individuals with specified a and f values
#' set.seed(1)
#' x <- make.inbreds(100, H, f = 0.02, a = 0.05, segments = TRUE)
#' hist(x$inbred.coef)
#' x$segments[[1]]


make.inbreds <- function(nb.inds, haplos, f, a, hbd.length, non.hbd.length, tile.length = 20, segments = FALSE) {
  if(all(haplos@snps$dist == 0))
    stop("Set genetic distance between markers with set.dist !")
 
  if(missing(hbd.length) | missing(non.hbd.length)) {
    hbd.length <- 1/(a*(1-f))
    non.hbd.length <- 1/(a*f)
  } else {
    if(!missing(a) | !missing(f))
    stop("Specify either f and a, or hbd.length and non.hbd.length")
  }
   
  L <- make_inbreds(nb.inds, hbd.length, non.hbd.length, tile.length, 
                  haplos@bed, haplos@snps$chr, haplos@snps$dist, segments)

  ped <- data.frame(famid = rep(1:nb.inds, each=2), id = c("A", "B"), father = NA, 
                    mother = NA, sex = NA, pheno = NA, stringsAsFactors = FALSE)
  
  x <- new("bed.matrix", bed = L$bed, snps = haplos@snps, ped = ped, p = NULL, mu = NULL,
           sigma = NULL, standardize_p = FALSE, standardize_mu_sigma = FALSE )
  
  if(getOption("gaston.auto.set.stats", TRUE))
    x <- set.stats(x)
  
  R <- list("bed.matrix" = x, "inbred.coef" = L$inb)
  if(segments) 
    R$segments <- lapply( L$segments, \(z) transform(z, chr = chr + 1) ) # chr numbering starting from 0/1
  R
}
