# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH_cpp <- function(B, sd, burn = 0L, thin = 1L) {
    .Call(`_Mozza_MH_cpp`, B, sd, burn, thin)
}

cousins_1stdegree <- function(n, tile_length, Haplos, chr, dist, kinship = FALSE) {
    .Call(`_Mozza_cousins_1stdegree`, n, tile_length, Haplos, chr, dist, kinship)
}

make_inds <- function(n, length_tiles, Haplos, chr, dist, kinship = FALSE) {
    .Call(`_Mozza_make_inds`, n, length_tiles, Haplos, chr, dist, kinship)
}

make_pairs <- function(N, le1, le2, length_tiles, Haplos, chr, dist) {
    .Call(`_Mozza_make_pairs`, N, le1, le2, length_tiles, Haplos, chr, dist)
}

nuclear_families <- function(nb_fams, nb_offsprings, tile_length, Haplos, chr, dist, kinship = FALSE) {
    .Call(`_Mozza_nuclear_families`, nb_fams, nb_offsprings, tile_length, Haplos, chr, dist, kinship)
}

essai <- function() {
    invisible(.Call(`_Mozza_essai`))
}

test_cursor <- function() {
    invisible(.Call(`_Mozza_test_cursor`))
}

essai2 <- function() {
    invisible(.Call(`_Mozza_essai2`))
}

essai3 <- function() {
    invisible(.Call(`_Mozza_essai3`))
}

essai3bis <- function() {
    invisible(.Call(`_Mozza_essai3bis`))
}

test_sharing <- function(n, le1 = 100., le2 = 100.) {
    .Call(`_Mozza_test_sharing`, n, le1, le2)
}

test_IBD_sibs <- function(n, n_haps = 100L, length_tiles = 20.) {
    .Call(`_Mozza_test_IBD_sibs`, n, n_haps, length_tiles)
}

test_push_genos <- function(H) {
    .Call(`_Mozza_test_push_genos`, H)
}

test_xptr <- function(Haplos, chr, dist) {
    .Call(`_Mozza_test_xptr`, Haplos, chr, dist)
}

families_of_4_v0 <- function(N, Haplos, chr, dist) {
    .Call(`_Mozza_families_of_4_v0`, N, Haplos, chr, dist)
}

families_of_4 <- function(N, Haplos, chr, dist) {
    .Call(`_Mozza_families_of_4`, N, Haplos, chr, dist)
}

