# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GQ <- function(phtab) {
    .Call(`_Mozza_GQ`, phtab)
}

GT <- function(phtab) {
    .Call(`_Mozza_GT`, phtab)
}

cousins_1stdegree <- function(n, tile_length, Haplos, chr, dist, kinship = FALSE, fraternity = FALSE) {
    .Call(`_Mozza_cousins_1stdegree`, n, tile_length, Haplos, chr, dist, kinship, fraternity)
}

drop_genotypes <- function(Z, Haplos, chr, dist) {
    .Call(`_Mozza_drop_genotypes`, Z, Haplos, chr, dist)
}

drop_genotypes_to_vcf <- function(Z, filename, Haplos, chr, dist, id, pos, A1, A2) {
    invisible(.Call(`_Mozza_drop_genotypes_to_vcf`, Z, filename, Haplos, chr, dist, id, pos, A1, A2))
}

haplo_drop_tile_index <- function(xpm, chr, pos) {
    .Call(`_Mozza_haplo_drop_tile_index`, xpm, chr, pos)
}

zygote_drop_tile_index <- function(xpz, chr, pos) {
    .Call(`_Mozza_zygote_drop_tile_index`, xpz, chr, pos)
}

getAutosomes <- function() {
    .Call(`_Mozza_getAutosomes`)
}

setAutosomes <- function(A) {
    invisible(.Call(`_Mozza_setAutosomes`, A))
}

getGenoVector <- function(pA, snpIndex, Rindex = TRUE) {
    .Call(`_Mozza_getGenoVector`, pA, snpIndex, Rindex)
}

haplo_group_by_tile_index <- function(xpm, chr, pos) {
    .Call(`_Mozza_haplo_group_by_tile_index`, xpm, chr, pos)
}

zygote_group_by_tile_index <- function(xpz, chr, pos) {
    .Call(`_Mozza_zygote_group_by_tile_index`, xpz, chr, pos)
}

haplotype_ <- function(ntiles, mean_length_tiles = 20) {
    .Call(`_Mozza_haplotype_`, ntiles, mean_length_tiles)
}

haplotype_probs <- function(probaTiles, mean_length_tiles = 20) {
    .Call(`_Mozza_haplotype_probs`, probaTiles, mean_length_tiles)
}

haplotype_peek <- function(xpm) {
    .Call(`_Mozza_haplotype_peek`, xpm)
}

zygote_peek <- function(xpz) {
    .Call(`_Mozza_zygote_peek`, xpz)
}

haplotype_poke <- function(xpm, tile_index, tile) {
    invisible(.Call(`_Mozza_haplotype_poke`, xpm, tile_index, tile))
}

zygote_poke <- function(xpz, tile_index1, tile1, tile_index2, tile2) {
    invisible(.Call(`_Mozza_zygote_poke`, xpz, tile_index1, tile1, tile_index2, tile2))
}

kinship_matrix_ <- function(L) {
    .Call(`_Mozza_kinship_matrix_`, L)
}

liabilitySelectedInds <- function(groupSize, minimumLiability, maximumLiability, length_tiles, Haplos, chr, dist, submap, beta, h2, kinship = FALSE, fraternity = FALSE) {
    .Call(`_Mozza_liabilitySelectedInds`, groupSize, minimumLiability, maximumLiability, length_tiles, Haplos, chr, dist, submap, beta, h2, kinship, fraternity)
}

liabilitySelectedIndsProbs <- function(groupSize, probaHaplos, probaDemes, liabilityOffsetDemes, minimumLiability, maximumLiability, length_tiles, Haplos, chr, dist, submap, beta, h2, kinship = FALSE, fraternity = FALSE) {
    .Call(`_Mozza_liabilitySelectedIndsProbs`, groupSize, probaHaplos, probaDemes, liabilityOffsetDemes, minimumLiability, maximumLiability, length_tiles, Haplos, chr, dist, submap, beta, h2, kinship, fraternity)
}

make_haps <- function(n, length_tiles, Haplos, chr, dist, ibd = FALSE) {
    .Call(`_Mozza_make_haps`, n, length_tiles, Haplos, chr, dist, ibd)
}

make_haps_probs <- function(N, proba_haplos, length_tiles, Haplos, chr, dist, ibd = FALSE) {
    .Call(`_Mozza_make_haps_probs`, N, proba_haplos, length_tiles, Haplos, chr, dist, ibd)
}

make_inbreds <- function(N, n_haps, le1, le2, length_tiles, segments = FALSE) {
    .Call(`_Mozza_make_inbreds`, N, n_haps, le1, le2, length_tiles, segments)
}

make_inds <- function(n, n_haps, length_tiles) {
    .Call(`_Mozza_make_inds`, n, n_haps, length_tiles)
}

make_inds_probs <- function(N, proba_haplos, length_tiles) {
    .Call(`_Mozza_make_inds_probs`, N, proba_haplos, length_tiles)
}

make_pairs <- function(N, le1, le2, length_tiles, Haplos, chr, dist) {
    .Call(`_Mozza_make_pairs`, N, le1, le2, length_tiles, Haplos, chr, dist)
}

nuclear_families <- function(nb_fams, nb_offsprings, tile_length, Haplos, chr, dist, kinship = FALSE, fraternity = FALSE) {
    .Call(`_Mozza_nuclear_families`, nb_fams, nb_offsprings, tile_length, Haplos, chr, dist, kinship, fraternity)
}

nuclear_families_probs <- function(Nfams, nb_offsprings, proba_haplos, length_tiles, Haplos, chr, dist, kinship = FALSE, fraternity = FALSE) {
    .Call(`_Mozza_nuclear_families_probs`, Nfams, nb_offsprings, proba_haplos, length_tiles, Haplos, chr, dist, kinship, fraternity)
}

pasteVcfElts <- function(genoN, rd, rd2, rd3, GQ, phtab) {
    .Call(`_Mozza_pasteVcfElts`, genoN, rd, rd2, rd3, GQ, phtab)
}

population <- function(n0, nGen, keep, lambda, tile_length, Haplos, chr, dist, kinship = FALSE, fraternity = FALSE) {
    .Call(`_Mozza_population`, n0, nGen, keep, lambda, tile_length, Haplos, chr, dist, kinship, fraternity)
}

reproduce_ <- function(z1, z2) {
    .Call(`_Mozza_reproduce_`, z1, z2)
}

reproduce_vec <- function(Z1, Z2) {
    .Call(`_Mozza_reproduce_vec`, Z1, Z2)
}

essai <- function() {
    invisible(.Call(`_Mozza_essai`))
}

test_cursor <- function() {
    invisible(.Call(`_Mozza_test_cursor`))
}

essai2 <- function() {
    invisible(.Call(`_Mozza_essai2`))
}

essai3 <- function() {
    invisible(.Call(`_Mozza_essai3`))
}

essai3bis <- function() {
    invisible(.Call(`_Mozza_essai3bis`))
}

test_IBD_sharing <- function(n, le1 = 100., le2 = 100.) {
    .Call(`_Mozza_test_IBD_sharing`, n, le1, le2)
}

test_IBD_sibs <- function(n, n_haps = 100L, length_tiles = 20.) {
    .Call(`_Mozza_test_IBD_sibs`, n, n_haps, length_tiles)
}

test_xptr <- function(Haplos, chr, dist) {
    .Call(`_Mozza_test_xptr`, Haplos, chr, dist)
}

families_of_4_v0 <- function(N, Haplos, chr, dist) {
    .Call(`_Mozza_families_of_4_v0`, N, Haplos, chr, dist)
}

families_of_4 <- function(N, Haplos, chr, dist) {
    .Call(`_Mozza_families_of_4`, N, Haplos, chr, dist)
}

write_hap_file <- function(p_A, filename) {
    invisible(.Call(`_Mozza_write_hap_file`, p_A, filename))
}

zygote_ <- function(ntiles, mean_length_tiles = 20) {
    .Call(`_Mozza_zygote_`, ntiles, mean_length_tiles)
}

zygote_probs <- function(probaTiles, mean_length_tiles = 20) {
    .Call(`_Mozza_zygote_probs`, probaTiles, mean_length_tiles)
}

